# -*- coding: utf-8 -*-
"""DEEP LEARNING.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZUIu_8nWBdXK7oeE2xGrWUsuQISRtstJ
"""

pip install tensorflow numpy matplotlib

#American Sign Language (ASL) Alphabet Recognition using Convolutional Neural Network (CNN) ~ TOPIC

# Deep Learning Course-Based Project
## Submitted by: VRUSHALI SAVANT
### Under the guidance of: Suresh Sir
#### Enrollment Number : 23STUCHH010296

#This project focuses on recognizing static hand gestures from the American Sign Language (ASL) alphabet using a Convolutional Neural Network (CNN).
#ASL is used widely within the deaf community for communication. Automating ASL recognition can help bridge communication gaps and build accessible technology.

## 1. Problem Statement
# Q-"The objective of this project is to develop a deep learning model capable of recognizing hand signs from the American Sign Language (ASL) alphabet.
#The model should classify an input image into one of the 24 ASL letters (A–Y except J and Z).
#CNNs are well suited for this task because they extract spatial features from images, enabling accurate gesture classification."

!pip install kaggle
!mkdir -p ~/.kaggle
!cp kaggle.json ~/.kaggle/
!chmod 600 ~/.kaggle/kaggle.json

# ===============================
# DATASET DETAILS (Required for Project)
# ===============================

# I am using the "Sign Language MNIST" dataset.
# Dataset Link: https://www.kaggle.com/datasets/datamunge/sign-language-mnist

# The dataset contains two CSV files:
# - sign_mnist_train.csv
# - sign_mnist_test.csv

# I uploaded both files manually to Google Colab using the left sidebar.
# The files visible in my Colab environment are:
# ['sign_mnist_train.csv', 'sign_mnist_test.csv']

# These files are automatically detected by the code below.

from google.colab import drive
drive.mount('/content/drive')
# You can copy files from /content/drive/MyDrive/... into working dir if needed

import os
os.listdir("/content")

import pandas as pd
import numpy as np

train = pd.read_csv("sign_mnist_train.csv")
test = pd.read_csv("sign_mnist_test.csv")

y_train = train['label'].values
X_train = train.drop('label', axis=1).values.reshape(-1,28,28,1)

y_test = test['label'].values
X_test = test.drop('label', axis=1).values.reshape(-1,28,28,1)

# Normalize
X_train = X_train / 255.0
X_test = X_test / 255.0

print("Train Shape:", X_train.shape)
print("Test Shape:", X_test.shape)

import tensorflow as tf
from tensorflow.keras import layers, models

model = models.Sequential([
    layers.Conv2D(32,(3,3),activation='relu',input_shape=(28,28,1)),
    layers.MaxPooling2D((2,2)),
    layers.Conv2D(64,(3,3),activation='relu'),
    layers.MaxPooling2D((2,2)),
    layers.Flatten(),
    layers.Dense(128,activation='relu'),
    layers.Dense(24,activation='softmax')  # 24 classes A-Y (J & Z missing)
])

model.compile(optimizer='adam',
              loss='sparse_categorical_crossentropy',
              metrics=['accuracy'])

model.summary()

model = models.Sequential([
    layers.Conv2D(32,(3,3),activation='relu',input_shape=(28,28,1)),
    layers.MaxPooling2D((2,2)),
    layers.Conv2D(64,(3,3),activation='relu'),
    layers.MaxPooling2D((2,2)),
    layers.Flatten(),
    layers.Dense(128,activation='relu'),
    layers.Dense(25,activation='softmax')   # <-- IMPORTANT FIX
])

model.compile(
    optimizer='adam',
    loss='sparse_categorical_crossentropy',
    metrics=['accuracy']
)

history = model.fit(
    X_train, y_train,
    validation_data=(X_test, y_test),
    epochs=10,
    batch_size=64
)

# These graphs show the model's training performance.
# The accuracy and loss curves demonstrate how the model learns over epochs.

import matplotlib.pyplot as plt

# Accuracy Curve
plt.figure(figsize=(6,4))
plt.plot(history.history['accuracy'], label='Train Accuracy')
plt.plot(history.history['val_accuracy'], label='Val Accuracy')
plt.title("Model Accuracy")
plt.xlabel("Epochs")
plt.ylabel("Accuracy")
plt.legend()
plt.grid()
plt.show()

# LOSS Curve
plt.figure(figsize=(6,4))
plt.plot(history.history['loss'], label='Train Loss')
plt.plot(history.history['val_loss'], label='Val Loss')
plt.title("Model Loss")
plt.xlabel("Epochs")
plt.ylabel("Loss")
plt.legend()
plt.grid()
plt.show()

import pandas as pd
import numpy as np

train = pd.read_csv("sign_mnist_train.csv")
test = pd.read_csv("sign_mnist_test.csv")

y_train = train['label'].values
X_train = train.drop('label', axis=1).values.reshape(-1,28,28,1)

y_test = test['label'].values
X_test = test.drop('label', axis=1).values.reshape(-1,28,28,1)

X_train = X_train / 255.0
X_test = X_test / 255.0

X_train.shape, X_test.shape

# This cell shows the working of my ASL CNN model.
# It displays 10 random test images, predicts the ASL alphabet class,
# and shows the true vs predicted labels.

import matplotlib.pyplot as plt
import numpy as np

# Select 10 random test samples
indices = np.random.randint(0, X_test.shape[0], 10)

plt.figure(figsize=(15,5))

for i, idx in enumerate(indices):
    img = X_test[idx]
    true_label = y_test[idx]

    pred = np.argmax(model.predict(img.reshape(1,28,28,1), verbose=0))

    plt.subplot(2,5,i+1)
    plt.imshow(img.reshape(28,28), cmap='gray')
    plt.title(f"True: {true_label} | Pred: {pred}")
    plt.axis('off')

plt.show()

import pandas as pd
import numpy as np
import tensorflow as tf
from tensorflow.keras import layers, models
from sklearn.preprocessing import LabelEncoder
import os

# --- Data Loading and Preprocessing ---

# Verify file existence
train_file_path = "/content/sign_mnist_train.csv"
test_file_path = "/content/sign_mnist_test.csv"

if not os.path.exists(train_file_path):
    print(f"Error: Training data file not found at {train_file_path}. Please re-upload it.")
elif not os.path.exists(test_file_path):
    print(f"Error: Test data file not found at {test_file_path}. Please re-upload it.")
else:
    train = pd.read_csv(train_file_path)
    test = pd.read_csv(test_file_path)

    y_train = train['label'].values
    X_train = train.drop('label', axis=1).values.reshape(-1,28,28,1)

    y_test = test['label'].values
    X_test = test.drop('label', axis=1).values.reshape(-1,28,28,1)

    # Normalize
    X_train = X_train / 255.0
    X_test = X_test / 255.0

    # Fix labels that are outside valid range
    valid_classes = 24   # 0–23 allowed
    y_train = np.where(y_train >= valid_classes, valid_classes - 1, y_train)
    y_test  = np.where(y_test >= valid_classes, valid_classes - 1, y_test)

    # Encode labels
    le = LabelEncoder()
    y_train = le.fit_transform(y_train)
    y_test  = le.transform(y_test)

    # --- End of Data Loading and Preprocessing ---

    model = models.Sequential([
        layers.Conv2D(32,(3,3),activation='relu',input_shape=(28,28,1)),
        layers.MaxPooling2D((2,2)),
        layers.Conv2D(64,(3,3),activation='relu'),
        layers.MaxPooling2D((2,2)),
        layers.Flatten(),
        layers.Dense(128,activation='relu'),
        layers.Dense(24,activation='softmax')   # Corrected to 24 classes
    ])

    model.compile(
        optimizer='adam',
        loss='sparse_categorical_crossentropy',
        metrics=['accuracy']
    )

    print("Starting model training to ensure model and data are initialized...")
    history = model.fit(
        X_train, y_train,
        validation_data=(X_test, y_test),
        epochs=10,
        batch_size=64
    )
    print("Model training complete. X_test, y_test, and model are now defined.")

import tensorflow as tf
from tensorflow.keras import layers, models

model = models.Sequential([
    layers.Conv2D(32,(3,3),activation='relu',input_shape=(28,28,1)),
    layers.MaxPooling2D((2,2)),
    layers.Conv2D(64,(3,3),activation='relu'),
    layers.MaxPooling2D((2,2)),
    layers.Flatten(),
    layers.Dense(128,activation='relu'),
    layers.Dense(25,activation='softmax')   # Corrected to 25 classes (0-24)
])

model.compile(
    optimizer='adam',
    loss='sparse_categorical_crossentropy',
    metrics=['accuracy']
)

# AGAIN NOW-> 1. DISPLAY SAMPLE IMAGES FROM DATASET
import matplotlib.pyplot as plt

# show first 25 training images
plt.figure(figsize=(10,10))
for i in range(25):
    plt.subplot(5,5,i+1)
    plt.imshow(X_train[i].reshape(28,28), cmap='gray')
    plt.title(f"Label: {y_train[i]}")
    plt.axis('off')
plt.show()

# MODEL PREDICTION ON VALIDATION DATA
import numpy as np

preds = model.predict(X_test)
pred_classes = np.argmax(preds, axis=1)

# Show first 25 validation images with predictions
plt.figure(figsize=(10,10))
for i in range(25):
    plt.subplot(5,5,i+1)
    plt.imshow(X_test[i].reshape(28,28), cmap='gray')
    plt.title(f"True:{y_test[i]} Pred:{pred_classes[i]}")
    plt.axis('off')
plt.show()

import tensorflow as tf
from tensorflow.keras import layers, models

model = models.Sequential([
    layers.Conv2D(32,(3,3),activation='relu',input_shape=(28,28,1)),
    layers.MaxPooling2D((2,2)),
    layers.Conv2D(64,(3,3),activation='relu'),
    layers.MaxPooling2D((2,2)),
    layers.Flatten(),
    layers.Dense(128,activation='relu'),
    layers.Dense(24,activation='softmax')   # Corrected to 24 classes
])

model.compile(
    optimizer='adam',
    loss='sparse_categorical_crossentropy',
    metrics=['accuracy']
)

# Fix labels that are outside valid range
valid_classes = 24   # 0–23 allowed

y_train = np.where(y_train >= valid_classes, valid_classes - 1, y_train)
y_test  = np.where(y_test >= valid_classes, valid_classes - 1, y_test)

from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()
y_train = le.fit_transform(y_train)
y_test  = le.transform(y_test)

import pandas as pd
import numpy as np
import tensorflow as tf
from tensorflow.keras import layers, models
from sklearn.preprocessing import LabelEncoder
import os



 (from previous cells) ---

# Verify file existence
train_file_path = "/content/sign_mnist_train.csv"
test_file_path = "/content/sign_mnist_test.csv"

if not os.path.exists(train_file_path):
    print(f"Error: Training data file not found at {train_file_path}. Please re-upload it.")
elif not os.path.exists(test_file_path):
    print(f"Error: Test data file not found at {test_file_path}. Please re-upload it.")
else:
    train = pd.read_csv(train_file_path)
    test = pd.read_csv(test_file_path)

    y_train = train['label'].values
    X_train = train.drop('label', axis=1).values.reshape(-1,28,28,1)

    y_test = test['label'].values
    X_test = test.drop('label', axis=1).values.reshape(-1,28,28,1)

    # Normalize
    X_train = X_train / 255.0
    X_test = X_test / 255.0

    # Fix labels that are outside valid range
    valid_classes = 24   # 0–23 allowed
    y_train = np.where(y_train >= valid_classes, valid_classes - 1, y_train)
    y_test  = np.where(y_test >= valid_classes, valid_classes - 1, y_test)

    # Encode labels
    le = LabelEncoder()
    y_train = le.fit_transform(y_train)
    y_test  = le.transform(y_test)

    # --- End of Data Loading and Preprocessing ---

    model = models.Sequential([
        layers.Conv2D(32,(3,3),activation='relu',input_shape=(28,28,1)),
        layers.MaxPooling2D((2,2)),
        layers.Conv2D(64,(3,3),activation='relu'),
        layers.MaxPooling2D((2,2)),
        layers.Flatten(),
        layers.Dense(128,activation='relu'),
        layers.Dense(24,activation='softmax')   # Corrected to 24 classes
    ])

    model.compile(
        optimizer='adam',
        loss='sparse_categorical_crossentropy',
        metrics=['accuracy']
    )

    history = model.fit(
        X_train, y_train,
        validation_data=(X_test, y_test),
        epochs=10,
        batch_size=64
    )